SET DEFINE OFF;

-- Inserta los vinos nacionales
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Santa Ema Amplus Cabernet Sauvignon', 'Chile', 2021, 85000, 45, 1);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Morandé Edición Limitada Carménère', 'Chile', 2020, 85000, 50, 1);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Casas del Bosque Botanic Series Chardonnay', 'Chile', 2022, 70000, 30, 1);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Caliterra Pétreo Malbec', 'Chile', 2021, 35000, 60, 1);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Viu Manent Secreto Rosé', 'Chile', 2023, 15000, 75, 1);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Morandé Vitis Unica Sauvignon Blanc', 'Chile', 2022, 68000, 40, 1);

-- Inserta los vinos importados
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Solar Viejo You & Me Albariño', 'España', 2022, 20000, 50, 2);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Luigi Bosca De Sangre Cabernet Sauvignon', 'Argentina', 2019, 21000, 30, 2);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('El Enemigo Chardonnay', 'Argentina', 2021, 41000, 20, 2);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Catena Zapata Angelica Zapata Malbec', 'Argentina', 2018, 72000, 15, 2);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Champagne Pol Roger Sir Winston Churchill', 'Francia', 2013, 470000, 10, 2);
INSERT INTO IMPOVINOS_VINO (NOMBRE, PAIS_ORIGEN, ANIO, PRECIO, STOCK, CATEGORIA_ID)
VALUES ('Freixenet Pinot Grigio', 'Italia', 2022, 22000, 25, 2);